# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'Obtaining SSH keys from Secret Manager' 
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    echo "Obtaining github credentials from secret manager"
    chmod 400 /root/.ssh/id_rsa
    cp cicd_pipeline/known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git' 
  id: 'Clone Repository'
  entrypoint: 'bash'
  args:
  - -c
  - |
    git clone "${_REPO}"
    
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'vol1'
    path: '/cortex-data-foundation'

- name: 'gcr.io/cloud-builders/git' 
  id: 'Merging and Pushing to Next Environment'
  entrypoint: 'bash'
  args:
  - -c
  - |
    cd cortex-data-foundation
    git config --global user.email "cortex-framework@point-star.com"
    git config --global user.name "cortex-poinstar"
    git switch "${_NEXT_BRANCH}"
    git merge -X theirs --no-edit "${_ENV}"
    git push origin "${_NEXT_BRANCH}"

#swap cherry pick with merge theirs    
#git cherry-pick origin/pointstar-main

  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'vol1'
    path: '/cortex-data-foundation'
    
logsBucket: "gs://${_GCS_BUCKET}"
substitutions:
  _REPO: "git@github.com:https-github-com-PointStarCloud/cortex-data-foundation.git"
availableSecrets:
  secretManager:
  - versionName: projects/my-int-cortex-0824/secrets/cortex-ssh-build/versions/latest
    env: 'SSH_KEY'
tags: ["cortex-cicd-pipeline-${_ENV}-git-push"]